version: "3.9"

services:
  php:
    build: ./
    container_name: phpunit
    tty: true
    volumes:
      - type: bind
        source: ./
        target: /app
      - type: bind
        source: ./php/php.ini
        target: /usr/local/etc/php/php.ini
